#!/bin/sh
#
# PROVIDE: ozwdaemon
# REQUIRE: DAEMON
# KEYWORD: shutdown
#
# ozwdaemon_enable: Set to YES to enable the ozwdaemon service.
#     Default: NO
# ozwdaemon_user: The user account used to run the ozwdaemon daemon.
#     This is optional, however do not specifically set this to an
#     empty string as this will cause the daemon to run as root.
#     Default: root
# ozwdaemon_group: The group account used to run the ozwdaemon daemon.
#     This is optional, however do not specifically set this to an
#     empty string as this will cause the daemon to run with group wheel.
#     Default: wheel
#
# ozw_config_dir: Directory containing the OZW Config Files.
#     Default:  "/root/config"
#
# ozw_user_dir: Directory for the OZW User Files.
#     Default:  "/root/config"
#
# ozw_mqtt_instance: OpenZWave Instance Number. If you want to run more than one
#     Z-Wave Network with multiple ozwdaemons, set this to a number greater than 1.
#     Default:  1
#     Change:   `sysrc ozw_mqtt_instance=2`
#     UnChange: `sysrc -x ozw_mqtt_instance`
#
# ozw_mqtt_port: MQTT Server Port.
#     Default:  1883
#     Change:   `sysrc ozw_mqtt_port=1984`
#     UnChange: `sysrc -x ozw_mqtt_port`
#
# ozw_mqtt_server: MQTT Server Hostname/IP Address.
#     Default:  localhost
#     Change:   `sysrc ozw_mqtt_server=192.168.10.100`
#     UnChange: `sysrc -x ozw_mqtt_server`
#
# ozw_usb_path: The Path to the USB Stick/Serial Device file in your jail.
#     Default:  /dev/cuaU0
#     Change:   `sysrc ozw_usb_path=/dev/ttyACM0`
#     UnChange: `srsrc -x ozw_usb_path

# -------------------------------------------------------
# Copy this file to '/usr/local/etc/rc.d/ozwdaemon' 
# `chmod +x /usr/local/etc/rc.d/ozwdaemon`
# `sysrc -f /etc/rc.conf ozwdaemon_enable=yes`
# `service ozwdaemon start`
# -------------------------------------------------------

. /etc/rc.subr
name=ozwdaemon
rcvar=${name}_enable

pidfile_child="/var/run/${name}.pid"
pidfile="/var/run/${name}_daemon.pid"
logfile="/var/log/${name}_daemon.log"

: ${ozwdaemon_enable:="NO"}
: ${ozwdaemon_user:="root"}
: ${ozwdaemon_group:="wheel"}
: ${ozw_config_dir:="/root/config"}
: ${ozw_user_dir:="/root/config"}
: ${ozw_usb_path:="/dev/cuaU0"}
: ${ozw_mqtt_instance:="1"}
: ${ozw_mqtt_port:="1883"}
: ${ozw_mqtt_server:="localhost"}

command="/usr/sbin/daemon"
extra_commands="logs restart"

logs_cmd=${name}_logs
ozwdaemon_logs() {
  tail -F "${logfile}"
}

restart_cmd="${name}_restart"
ozwdaemon_restart() {
  run_rc_command stop  #>/dev/null 2>&1
  sleep 2
  run_rc_command start #>/dev/null 2>&1
}

start_precmd=${name}_precmd
ozwdaemon_precmd() {
  local _workdir="/root"
  cd "${_workdir}"
  
  local _config="${_workdir}/.ozw_profile"
  if [ -f "${_config}" ]; then
    echo "Loading Enviroment Variables from ${_config}"
    . "${_config}"
  fi
  
  if [ ! -c ${USB_PATH:=${ozw_usb_path}} ]; then
    echo "USB Path ${USB_PATH} does not exist or is not a Character Device"
    exit 128
  fi
  
  OZW_ARGS=""
  OZW_ARGS=" -s ${USB_PATH} \
    --config-dir ${OZW_CONFIG_DIR:=${ozw_config_dir}} \
    --user-dir ${OZW_USER_DIR:=${ozw_user_dir}} \
    --mqtt-instance ${MQTT_INSTANCE:=${ozw_mqtt_instance}} \
    --mqtt-port ${MQTT_PORT:=${ozw_mqtt_port}} \
    --mqtt-server ${MQTT_SERVER:=${ozw_mqtt_server}}"

  if [ ! -z "${MQTT_USERNAME:=${ozw_mqtt_user}}" ]; then
    OZW_ARGS="${OZW_ARGS} --mqtt-username ${MQTT_USERNAME}"
  fi
  
  if [ "${MQTT_TLS:=false}" == true ]; then
    OZW_ARGS="${OZW_ARGS} --mqtt-tls"
  elif [ "$MQTT_TLS" != false ]; then
    echo "Invalid value for MQTT_TLS: \"$MQTT_TLS\", expected true or false."
    exit 1
  fi
  
  if [ "${STOP_ON_FAILURE:=true}" == true ]; then
    OZW_ARGS="${OZW_ARGS} --stop-on-failure"
  elif [ "$STOP_ON_FAILURE" != "false" ]; then
    echo "Invalid value for STOP_ON_FAILURE: \"$STOP_ON_FAILURE\", expected true or false."
    exit 1
  fi

  rc_flags="-f -o ${logfile} -P ${pidfile} -p ${pidfile_child} /usr/local/bin/ozwdaemon ${OZW_ARGS}" ${rc_flags}
  
  [ -e "${logfile}" ] && rm -f -- "${logfile}"
  install -g ${ozwdaemon_group} -o ${ozwdaemon_user} -- /dev/null "${logfile}"
}

start_postcmd=${name}_poststart
ozwdaemon_poststart() {
  sleep 1
  run_rc_command status
}

stop_postcmd=${name}_poststop
ozwdaemon_poststop() {
  rm -f -- "${pidfile}"
  rm -f -- "${pidfile_child}"
}

load_rc_config ${name}
run_rc_command "$1"
